# Generated by Django 4.2.1 on 2023-05-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('total_trabajadores', models.IntegerField(verbose_name='total_trabajadores')),
                ('trabajadores_discapacitados', models.IntegerField(verbose_name='trabajadores_discapacitados')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='tablaEncuestaRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoEdad', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('hombre', models.IntegerField()),
                ('Mujer', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Encuesta Rural',
            },
        ),
        migrations.CreateModel(
            name='tablaEncuestaUrbana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoEdad', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('hombre', models.IntegerField()),
                ('Mujer', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Encuesta Urbana',
            },
        ),
        migrations.CreateModel(
            name='tablaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('hombre', models.IntegerField()),
                ('mujer', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'tabla Nivel',
            },
        ),
    ]
