# Generated by Django 4.2.1 on 2023-05-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablaencuestarural',
            old_name='Mujer',
            new_name='mujer',
        ),
        migrations.RenameField(
            model_name='tablaencuestaurbana',
            old_name='Mujer',
            new_name='mujer',
        ),
    ]
