# Generated by Django 4.2.1 on 2023-05-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0003_tablacategoria_tablatipodiscapacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablatipodiscapacidad',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='tablatipodiscapacidad',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='numero_Desocupadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='numero_Inactivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='numero_Ocupadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='porcentaje_Desocupadas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='porcentaje_Inactivas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tablatipodiscapacidad',
            name='porcentaje_Ocupadas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tablatipodiscapacidad',
            name='discapacidad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
