# Generated by Django 4.2.1 on 2023-05-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0005_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.AlterModelOptions(
            name='resumen',
            options={'verbose_name_plural': 'Resumen'},
        ),
    ]
