# Generated by Django 4.2.1 on 2023-05-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('poblacion', models.IntegerField(verbose_name='poblacion')),
                ('poblacion_discapacitados', models.IntegerField(verbose_name='poblacion_discapacitados')),
            ],
            options={
                'verbose_name_plural': 'Universidad',
            },
        ),
    ]
