# Generated by Django 4.2.1 on 2023-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes_Activos_IES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('fisica', models.IntegerField()),
                ('intelectual', models.IntegerField()),
                ('sensorial', models.IntegerField()),
                ('mental', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estudiantes activos IES 2018-2020',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_Genero_Tipo_2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='discapacidad')),
                ('masculino', models.IntegerField()),
                ('femenino', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estudiantes por Genero y Discapacidad (2018)',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_Genero_Tipo_2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='discapacidad')),
                ('masculino', models.IntegerField()),
                ('femenino', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estudiantes por Genero y Discapacidad (2019)',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_Genero_Tipo_2020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='discapacidad')),
                ('masculino', models.IntegerField()),
                ('femenino', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estudiantes por Genero y Discapacidad (2020)',
            },
        ),
        migrations.CreateModel(
            name='Prevalencia_Estudiantes_Activos_IES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='discapacidad')),
                ('año_2018', models.IntegerField()),
                ('año_2019', models.IntegerField()),
                ('año_2020', models.IntegerField()),
                ('total', models.IntegerField()),
                ('porcentaje', models.CharField(max_length=50, verbose_name='porcentaje')),
            ],
            options={
                'verbose_name_plural': 'Prevalencia de Discapacidad (2018-2020)',
            },
        ),
    ]
