# Generated by Django 4.2.1 on 2023-06-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0002_estudiantes_activos_ies_estudiantes_genero_tipo_2018_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.CreateModel(
            name='resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resumen',
            },
        ),
    ]
